### ISSUE TITLE
pillow problem

### ISSUE THREAD

**Issue by ZSM2MTROY** [alimama-creative/SDXL_EcomID_ComfyUI#24]
Argument interpolation should be an `InterpolationMode` or a corresponding Pillow integer constant, but got InterpolationMode.BICUBIC.

**Comment by ZSM2MTROY** [comment]
!!! Exception during processing !!! Argument interpolation should be an `InterpolationMode` or a corresponding Pillow integer constant, but got InterpolationMode.BICUBIC.
Traceback (most recent call last):
  File "E:\blibli comfyui\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blibli comfyui\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blibli comfyui\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\blibli comfyui\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blibli comfyui\custom_nodes\SDXL_EcomID_ComfyUI\EcomID.py", line 528, in apply_EcomID
    face_features_image = T.functional.resize(face_features_image, eva_clip.image_size,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blibli comfyui\.ext\Lib\site-packages\torchvision\transforms\v2\functional\_geometry.py", line 188, in resize
    return kernel(inpt, size=size, interpolation=interpolation, max_size=max_size, antialias=antialias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blibli comfyui\.ext\Lib\site-packages\torchvision\transforms\v2\functional\_geometry.py", line 214, in resize_image
    interpolation = _check_interpolation(interpolation)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blibli comfyui\.ext\Lib\site-packages\torchvision\transforms\v2\functional\_geometry.py", line 34, in _check_interpolation
    raise ValueError(
ValueError: Argument interpolation should be an `InterpolationMode` or a corresponding Pillow integer constant, but got InterpolationMode.BICUBIC.

**Comment by dee0210** [comment]
解决了吗
